import * as React from 'react';
import { View, Pressable, Platform, ScrollView } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Text } from './Text';
import { Card } from './Card';
import { Avatar } from './Avatar';
import { usePosts, useCommunities, useProfiles } from '../lib/hooks';
import { colors, spacing } from '../constants/theme';

function TrendingPosts() {
  const { posts } = usePosts('score', 5);
  const router = useRouter();
  const trending = posts.slice(0, 5);

  return (
    <Card>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.md }}>
        <Ionicons name="trending-up" size={16} color={colors.accent} />
        <Text variant="bodyMedium" style={{ fontSize: 14 }}>Trending</Text>
      </View>
      {trending.length === 0 ? (
        <Text variant="caption" color={colors.textMuted}>No trending posts yet</Text>
      ) : (
        trending.map((post: any, i: number) => (
          <Pressable
            key={post.id}
            onPress={() => router.push(`/(tabs)/post/${post.id}` as any)}
            style={({ pressed }) => ({
              paddingVertical: spacing.sm,
              borderTopWidth: i > 0 ? 1 : 0,
              borderTopColor: 'rgba(255,255,255,0.06)',
              opacity: pressed ? 0.7 : 1,
              ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}),
            })}
          >
            <Text variant="bodyMedium" numberOfLines={1} style={{ fontSize: 13 }}>
              {post.title || post.content?.slice(0, 60) || 'Untitled'}
            </Text>
            <Text variant="caption" color={colors.textMuted} style={{ fontSize: 12, marginTop: 2 }}>
              {post.score || 0} pts
            </Text>
          </Pressable>
        ))
      )}
    </Card>
  );
}

function SuggestedPeople() {
  const { profiles } = useProfiles(5);
  const router = useRouter();

  if (profiles.length === 0) return null;

  return (
    <Card>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.md }}>
        <Ionicons name="sparkles" size={16} color={colors.accent} />
        <Text variant="bodyMedium" style={{ fontSize: 14 }}>Suggested</Text>
      </View>
      {profiles.slice(0, 5).map((u: any, i: number) => {
        const name = u.name || 'User';
        const username = u.username || '';
        const isAutoGenerated = username.includes('+') || /^[a-f0-9]{8,}$/i.test(username) || username.includes('@');
        return (
          <Pressable
            key={u.id}
            onPress={() => router.push(`/(tabs)/user/${u.username || u.id}` as any)}
            style={({ pressed }) => ({
              flexDirection: 'row',
              alignItems: 'center',
              gap: spacing.md,
              paddingVertical: spacing.sm,
              borderTopWidth: i > 0 ? 1 : 0,
              borderTopColor: 'rgba(255,255,255,0.06)',
              opacity: pressed ? 0.7 : 1,
              ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}),
            })}
          >
            <Avatar uri={u.image} name={name} size="sm" />
            <View style={{ flex: 1 }}>
              <Text variant="bodyMedium" numberOfLines={1} style={{ fontSize: 13 }}>
                {name}
              </Text>
              {!isAutoGenerated && username && (
                <Text variant="caption" color={colors.textMuted} numberOfLines={1} style={{ fontSize: 11 }}>
                  @{username}
                </Text>
              )}
            </View>
          </Pressable>
        );
      })}
    </Card>
  );
}

function CommunitiesList() {
  const { communities } = useCommunities(5);
  const router = useRouter();

  if (communities.length === 0) return null;

  return (
    <Card>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.md }}>
        <Ionicons name="people" size={16} color={colors.accent} />
        <Text variant="bodyMedium" style={{ fontSize: 14 }}>Communities</Text>
      </View>
      {communities.slice(0, 5).map((c: any, i: number) => (
        <Pressable
          key={c.id}
          onPress={() => router.push(`/(tabs)/community/${c.id}` as any)}
          style={({ pressed }) => ({
            flexDirection: 'row',
            alignItems: 'center',
            gap: spacing.md,
            paddingVertical: spacing.sm,
            borderTopWidth: i > 0 ? 1 : 0,
            borderTopColor: 'rgba(255,255,255,0.06)',
            opacity: pressed ? 0.7 : 1,
            ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}),
          })}
        >
          <Avatar uri={c.image} name={c.name} size="sm" />
          <View style={{ flex: 1 }}>
            <Text variant="bodyMedium" numberOfLines={1} style={{ fontSize: 13 }}>{c.name}</Text>
            <Text variant="caption" color={colors.textMuted} style={{ fontSize: 11 }}>
              {c.memberCount || 0} members
            </Text>
          </View>
        </Pressable>
      ))}
    </Card>
  );
}

export function FeedSidebar() {
  return (
    <ScrollView
      style={{
        width: '100%' as any,
        ...(Platform.OS === 'web'
          ? { position: 'sticky' as any, top: 0, maxHeight: '100vh' as any }
          : {}),
      }}
      contentContainerStyle={{
        gap: spacing.lg,
        paddingTop: spacing.lg,
        paddingBottom: spacing['4xl'],
      }}
      showsVerticalScrollIndicator={false}
    >
      <TrendingPosts />
      <SuggestedPeople />
      <CommunitiesList />
    </ScrollView>
  );
}
